### ISSUE TITLE
Request to add GitHub Topics : 'las-files' and 'log-ascii-standard' to the GitHub About section.

### ISSUE THREAD

**Issue by dcslagel** [MandarJKulkarni/lascheck#10]
It would be helpful to others looking for this tool if related GitHub Topic's  'las-files' and 'log-ascii-standard'  were added to the About section of the main GitHub lascheck section.  Only the owner has permission to add these.   Could these be added?

Thank you,
DC

**Comment by MandarJKulkarni** [comment]
Done. Thanks!

**Comment by dcslagel** [comment]
Good!  Hopefully more people with find LasCheck and give it a try.   Closing this issue.

Thank you, 
DC
